package com.csigroup.model;

// Generated Aug 21, 2015 2:16:57 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Transient;


/**
 * TblAuthMprogram generated by hbm2java
 */
public class AuthMProgram implements java.io.Serializable,Cloneable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int programId;
	private int version;
	private String programCode;
	private String programNameTh;
	private String programNameEn;
	private String url;
	private String createBy;
	private Date createDate;
	private String updateBy;
	private Date updateDate;
	
	//temp 
	private boolean selected;
	private String programNameByLocal;

	public AuthMProgram() {
	}

	public AuthMProgram(int programId, String programCode,
			String programNameTh, String programNameEn, String url,
			String createBy, Date createDate) {
		this.programId = programId;
		this.programCode = programCode;
		this.programNameTh = programNameTh;
		this.programNameEn = programNameEn;
		this.url = url;
		this.createBy = createBy;
		this.createDate = createDate;
	}

	public AuthMProgram(int programId, String programCode,
			String programNameTh, String programNameEn, String url,
			String createBy, Date createDate, String updateBy,
			Date updateDate) {
		this.programId = programId;
		this.programCode = programCode;
		this.programNameTh = programNameTh;
		this.programNameEn = programNameEn;
		this.url = url;
		this.createBy = createBy;
		this.createDate = createDate;
		this.updateBy = updateBy;
		this.updateDate = updateDate;
	}

	public int getProgramId() {
		return this.programId;
	}

	public void setProgramId(int programId) {
		this.programId = programId;
	}

	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	public String getProgramCode() {
		return this.programCode;
	}

	public void setProgramCode(String programCode) {
		this.programCode = programCode;
	}

	public String getProgramNameTh() {
		return this.programNameTh;
	}

	public void setProgramNameTh(String programNameTh) {
		this.programNameTh = programNameTh;
	}

	public String getProgramNameEn() {
		return this.programNameEn;
	}

	public void setProgramNameEn(String programNameEn) {
		this.programNameEn = programNameEn;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public String getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Override
	public Object clone() throws CloneNotSupportedException {
		return super.clone();
	}

	public boolean isSelected() {
		return selected;
	}

	public void setSelected(boolean selected) {
		this.selected = selected;
	}

	public void setProgramNameByLocal(String programNameByLocal) {
		this.programNameByLocal = programNameByLocal;
	}
}
